# -*- coding: utf-8 -*-
"""AILab-MidTerm.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZpHD2UHSt_19nGsKtRC53xe25os5kXFm
"""

"""
Constraint Satisfaction Problem Lab
-----------------------------------

Problem:
    Color each region of a map using 4 colors so that neighboring
    regions have different colors.

1. Basic backtracking:
       - fixed variable ordering
       - filtering against assigned variables

2. Improved backtracking:
       - MRV variable ordering
       - forward checking
       - AC-3 constraint propagation

The program counts search nodes so that the amount of exploration
can be compared.
"""

from copy import deepcopy
from collections import deque


COLORS = ["Red", "Green", "Blue", "Yellow"]

EDGES = [
    ("A", "B"),
    ("A", "C"),
    ("A", "D"),
    ("B", "C"),
    ("B", "E"),
    ("B", "F"),
    ("C", "D"),
    ("C", "E"),
    ("C", "F"),
    ("D", "E"),
    ("D", "G"),
    ("E", "F"),
    ("E", "G"),
    ("E", "H"),
    ("F", "G"),
    ("F", "H"),
    ("G", "H"),
]

VARIABLES = sorted(set(x for edge in EDGES for x in edge)) #Or can be directly assigned : VARIABLES=set(A,B,C,D,E,F,G)

DOMAINS = {
    variable: COLORS.copy()
    for variable in VARIABLES
}


def build_neighbors(edges):
    neighbors = {v: set() for v in VARIABLES}

    for x, y in edges:
        neighbors[x].add(y)
        neighbors[y].add(x)

    return neighbors


NEIGHBORS = build_neighbors(EDGES)


def is_consistent(variable, value, assignment):
    for neighbor in NEIGHBORS[variable]:
        if neighbor in assignment:
            if assignment[neighbor] == value:
                return False

    return True


class SearchStats:
    def __init__(self):
        self.nodes = 0


def basic_backtracking(assignment, domains, stats):
    if len(assignment) == len(VARIABLES):
        return assignment.copy()

    variable = next(
        v for v in VARIABLES
        if v not in assignment
    )

    for value in domains[variable]:
        stats.nodes += 1

        if is_consistent(variable, value, assignment):
            assignment[variable] = value

            result = basic_backtracking(
                assignment,
                domains,
                stats
            )

            if result is not None:
                return result

            del assignment[variable]

    return None


def forward_check(variable, value, assignment, domains):
    new_domains = deepcopy(domains)
    new_domains[variable] = [value]

    for neighbor in NEIGHBORS[variable]:
        if neighbor in assignment:
            continue

        if value in new_domains[neighbor]:
            new_domains[neighbor].remove(value)

        if len(new_domains[neighbor]) == 0:
            return None

    return new_domains


def revise(domains, x, y):
    revised = False

    for x_value in domains[x][:]:
        supported = any(
            x_value != y_value
            for y_value in domains[y]
        )

        if not supported:
            domains[x].remove(x_value)
            revised = True

    return revised


def ac3(domains):
    queue = deque()

    for x in VARIABLES:
        for y in NEIGHBORS[x]:
            queue.append((x, y))

    while queue:
        x, y = queue.popleft()

        if revise(domains, x, y):
            if len(domains[x]) == 0:
                return False

            for z in NEIGHBORS[x]:
                if z != y:
                    queue.append((z, x))

    return True


def select_mrv_variable(assignment, domains):
    unassigned = [
        v for v in VARIABLES
        if v not in assignment
    ]

    return min(
        unassigned,
        key=lambda v: len(domains[v])
    )


def improved_backtracking(assignment, domains, stats):
    if len(assignment) == len(VARIABLES):
        return assignment.copy()

    variable = select_mrv_variable(
        assignment,
        domains
    )

    for value in domains[variable]:
        stats.nodes += 1

        if not is_consistent(variable, value, assignment):
            continue

        new_domains = forward_check(
            variable,
            value,
            assignment,
            domains
        )

        if new_domains is None:
            continue

        if not ac3(new_domains):
            continue

        assignment[variable] = value

        result = improved_backtracking(
            assignment,
            new_domains,
            stats
        )

        if result is not None:
            return result

        del assignment[variable]

    return None


def main():
    print("=" * 60)
    print("CONSTRAINT SATISFACTION PROBLEM")
    print("Graph Coloring")
    print("=" * 60)

    print("\nVariables:")
    print(VARIABLES)

    print("\nColors:")
    print(COLORS)

    print("\nConstraints:")
    for x, y in EDGES:
        print(f"  {x} != {y}")

    basic_stats = SearchStats()

    basic_solution = basic_backtracking(
        assignment={},
        domains=deepcopy(DOMAINS),
        stats=basic_stats
    )

    improved_stats = SearchStats()

    improved_solution = improved_backtracking(
        assignment={},
        domains=deepcopy(DOMAINS),
        stats=improved_stats
    )

    print("\n" + "=" * 60)
    print("BASIC BACKTRACKING")
    print("=" * 60)

    print("Solution:")
    print(basic_solution)

    print("Nodes explored:",
          basic_stats.nodes)

    print("\n" + "=" * 60)
    print("IMPROVED BACKTRACKING")
    print("=" * 60)

    print("Solution:")
    print(improved_solution)

    print("Nodes explored:",
          improved_stats.nodes)

    print("\n" + "=" * 60)
    print("COMPARISON")
    print("=" * 60)

    if improved_stats.nodes < basic_stats.nodes:
        reduction = (
            100
            * (basic_stats.nodes - improved_stats.nodes)
            / basic_stats.nodes
        )

        print(
            f"Basic search explored:     {basic_stats.nodes}"
        )
        print(
            f"Improved search explored:  {improved_stats.nodes}"
        )
        print(
            f"Reduction in exploration:  {reduction:.1f}%"
        )

    elif improved_stats.nodes == basic_stats.nodes:
        print("Both methods explored the same number of nodes.")

    else:
        print(
            "The improved solver explored more nodes on "
            "this particular instance."
        )


if __name__ == "__main__":
    main()

"""
Dijkstra's Algorithm - Grid Pathfinding
-----------------------------------------------
Finds the shortest path from S (start) to G (goal) on a fixed grid,
where '#' cells are walls and every step costs 1.

YOUR TASK: adapt this into A* search.
"""

import heapq

ROWS, COLS = 12, 16
START = (0, 0)
GOAL = (11, 15)

_GRID_ROWS = [
    "S....#.......#..",
    ".....#.......#..",
    ".....#........##",
    ".....#..........",
    ".....#....#.....",
    ".....#.#..#.....",
    ".....#....#.....",
    ".....#....#.....",
    "..........#.####",
    "..........#.....",
    "..........#.####",
    "..........#....G",
]


def generate_grid():
    return [list(row) for row in _GRID_ROWS]


def print_grid(grid, path=None, visited=None, title=""):
    print(f"\n--- {title} ---")
    display = [row.copy() for row in grid]
    if visited:
        for (r, c) in visited:
            if display[r][c] == '.':
                display[r][c] = ','
    if path:
        for (r, c) in path:
            if display[r][c] not in ('S', 'G'):
                display[r][c] = '*'
    for row in display:
        print(' '.join(row))


def neighbors(grid, node):
    r, c = node
    rows, cols = len(grid), len(grid[0])
    result = []
    for dr, dc in [(-1, 0), (1, 0), (0, -1), (0, 1)]:
        nr, nc = r + dr, c + dc
        if 0 <= nr < rows and 0 <= nc < cols and grid[nr][nc] != '#':
            result.append(((nr, nc), 1))
    return result


def reconstruct_path(came_from, current):
    path = [current]
    while current in came_from:
        current = came_from[current]
        path.append(current)
    path.reverse()
    return path


def dijkstra(grid, start, goal, verbose_steps=10):
    open_set = [(0, start)]
    came_from = {}
    g_score = {start: 0}
    visited_order = []
    closed = set()
    step = 0

    print(f"First {verbose_steps} pops from the priority queue:")
    while open_set:
        g, current = heapq.heappop(open_set)

        if current in closed:
            continue
        closed.add(current)
        visited_order.append(current)

        step += 1
        if step <= verbose_steps:
            print(f"  step {step:3d}: pop {current}  g={g:2d}")

        if current == goal:
            path = reconstruct_path(came_from, current)
            return path, visited_order, g_score[goal]

        for neighbor, cost in neighbors(grid, current):
            tentative_g = g + cost
            if tentative_g < g_score.get(neighbor, float('inf')):
                came_from[neighbor] = current
                g_score[neighbor] = tentative_g
                heapq.heappush(open_set, (tentative_g, neighbor))

    return None, visited_order, None


if __name__ == "__main__":
    grid = generate_grid()

    print("GRID SETUP")
    print(f"Rows x Cols : {ROWS} x {COLS}")
    print(f"Start       : {START}")
    print(f"Goal        : {GOAL}")
    print_grid(grid, title="Initial Grid (S=start, G=goal, #=wall)")

    print("\n" + "=" * 60)
    print("DIJKSTRA'S ALGORITHM")
    print("=" * 60)
    path, visited, cost = dijkstra(grid, START, GOAL)
    print_grid(grid, path=path, visited=visited,
               title="Dijkstra result: visited=',' path='*'")

    print(f"\nShortest path cost : {cost}")
    print(f"Path                : {path}")
    print(f"Total nodes expanded: {len(visited)}  (out of {ROWS * COLS} cells)")

